export const data = {
  value: 100,
  users: [
    {
      name: "The Boy",
      email: "theboy@gmail.com",
      img: "/boy.png",
      subscription: false,
      price: 400,
    },
    {
      name: "GURU G",
      email: "gurug@gmail.com",
      img: "/guru.png",
      subscription: false,
      price: 100,
    },
    {
      name: "Afzal Bey",
      email: "afzalbeyo@gmail.com",
      img: "/profile.png",
      subscription: true,
      price: 200,
    },
    {
      name: "V Vite",
      email: "vvite@gmail.com",
      img: "/vite.svg",
      subscription: true,
      price: 1000,
    },
    {
      name: "The Boy 2",
      email: "theboy2@gmail.com",
      img: "/boy.png",
      subscription: false,
      price: 400,
    },
    {
      name: "Guru Ka G",
      email: "gurukag@gmail.com",
      img: "/guru.png",
      subscription: false,
      price: 100,
    },
    {
      name: "Muhammad Afzal",
      email: "mafzalbro@gmail.com",
      img: "/profile.png",
      subscription: true,
      price: 200,
    },
    {
      name: "Vite",
      email: "vite@gmail.com",
      img: "/vite.svg",
      subscription: true,
      price: 1000,
    },
  ],
};
